apiVersion: apps/v1
kind: Deployment
metadata:
   name: aplicacao-noticia-deployment
spec:
   replicas: 2
   selector: 
      matchLabels:
         name: aplicacao-noticia-pod
   template:
      metadata:
         labels:
           name: aplicacao-noticia-pod
      spec:
        containers:
        - name: container-aplicacao
          image: ramimar/noticia-alura:v2
          ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
   name: servico-aplicacao-noticia
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 31500
  selector:
    name: aplicacao-noticia-pod
#   externalIPs:
#     - 192.168.0.108
