apiVersion: apps/v1
kind: Deployment
metadata:
   name: aplicacao-sistema-deployment
spec:
   replicas: 5
   selector: 
      matchLabels:
         name: aplicacao-sistema-pod
   template:
      metadata:
         labels:
           name: aplicacao-sistema-pod
      spec:
        containers:
        - name: container-aplicacao-sistema
          image: ramimar/sistema-noticia-alura:v1
          ports:
          - containerPort: 80
