apiVersion: v1
kind: Service
metadata:
   name: servico-aplicacao-noticia
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 31500
  selector:
    name: aplicacao-noticia-pod
#   externalIPs:
#     - 192.168.0.108
