apiVersion: v1
kind: Service
metadata:
   name: servico-sistema-noticia-statefulset
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 80
      nodePort: 31600
  selector:
    name: aplicacao-sistema-pod-statefulset


